export const words = [
    'algorithm',
    'analysis',
    'architecture',
    'database',
    'encryption',
    'framework',
    'interface',
    'machine learning',
    'model',
    'network',
    'optimization',
    'protocol',
    'query',
    'simulation',
    'system',
    'technology',
    'validation',
    'visualization',
    'workflow',
    'xenon',
    'cs',
    'compsci',
    'comsci',
    'computer science',
    'cics',
    'information',
    'automata',
    'oop',
    'object-oriented programming',
    'object oriented',
    'java',
    'javascript',
    'library',
    'library system',
    'crud',
    'data cloud'
  ];
  
